=== radwanabil/XML/Lab3/part1/lab3.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- W3C Schema generated by XMLSpy v2023 sp1 (x64) (http://www.altova.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="address">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="street"/>
				<xs:element ref="city"/>
				<xs:element ref="country"/>
				<xs:element ref="building"/>
				<xs:element ref="region"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="addresses">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="address" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="building">
		<xs:simpleType>
			<xs:restriction base="xs:anyURI">
				<xs:enumeration value="Building: 10"/>
				<xs:enumeration value="Building: 15"/>
				<xs:enumeration value="Building: 19"/>
				<xs:enumeration value="Building: 50"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="city">
		<xs:simpleType>
			<xs:restriction base="xs:anyURI">
				<xs:enumeration value="City: alex"/>
				<xs:enumeration value="City: cairo"/>
				<xs:enumeration value="City: damnhour"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="country">
		<xs:simpleType>
			<xs:restriction base="xs:anyURI">
				<xs:enumeration value="Country: Egypt"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="email">
		<xs:simpleType>
			<xs:restriction base="xs:anyURI">
				<xs:enumeration value="Email: radwa@gmail.com"/>
				<xs:enumeration value="Email: rima@yahoo.com"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="employee">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="name"/>
				<xs:choice>
					<xs:element ref="phones"/>
					<xs:element ref="phone" maxOccurs="unbounded"/>
				</xs:choice>
				<xs:element ref="addresses"/>
				<xs:element ref="email"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="employees">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="employee" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="name">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Employee Name: Radwa Nabil"/>
				<xs:enumeration value="Employee Name: Rima Nabil"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="phone">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="ST_phone">
					<xs:attribute name="type" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="home"/>
								<xs:enumeration value="mobile"/>
								<xs:enumeration value="work"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="phones">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="phone" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="region">
		<xs:simpleType>
			<xs:restriction base="xs:anyURI">
				<xs:enumeration value="Region: mohram beek"/>
				<xs:enumeration value="Region: sidi beshr"/>
				<xs:enumeration value="Region: smouha"/>
				<xs:enumeration value="Region: sporting"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="street">
		<xs:simpleType>
			<xs:restriction base="xs:anyURI">
				<xs:enumeration value="Street: 12 Main St."/>
				<xs:enumeration value="Street: 123 Main St."/>
				<xs:enumeration value="Street: 128 Main St."/>
				<xs:enumeration value="Street: 19 Main St."/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:simpleType name="ST_phone">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Home phone: 0398798980"/>
			<xs:enumeration value="Mobile phone: 01154576987"/>
			<xs:enumeration value="Mobile phone: 01287809888"/>
			<xs:enumeration value="Work phone: 0125786790"/>
			<xs:enumeration value="Work phone: 0128989009"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== radwanabil/XML/Lab3/part1/lab3.xml
<?xml version="1.0" encoding="UTF-8"?>
<employees xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/Users/Radwa%20Nabil/OneDrive/Documents/Altova/XMLSpy2023/Examples/lab3.xsd">
	<employee>
		<name>Employee Name: Radwa Nabil</name>
		<phones>
			<phone type="work">Work phone: 0128989009</phone>
			<phone type="mobile">Mobile phone: 01154576987</phone>
			<phone type="home">Home phone: 0398798980</phone>
		</phones>
		<addresses>
			<address>
				<street>Street: 123 Main St.</street>
				<city>City: alex</city>
				<country>Country: Egypt</country>
				<building>Building: 15</building>
				<region>Region: sporting</region>
			</address>
			<address>
				<street>Street: 128 Main St.</street>
				<city>City: cairo</city>
				<country>Country: Egypt</country>
				<building>Building: 50</building>
				<region>Region: mohram beek</region>
			</address>
		</addresses>
		<email>Email: radwa@gmail.com</email>
	</employee>
	<employee>
		<name>Employee Name: Rima Nabil</name>
		<phone type="work">Work phone: 0125786790</phone>
		<phone type="mobile">Mobile phone: 01287809888</phone>
		<phone type="home">Home phone: 0398798980</phone>
		<addresses>
			<address>
				<street>Street: 12 Main St.</street>
				<city>City: alex</city>
				<country>Country: Egypt</country>
				<building>Building: 10</building>
				<region>Region: smouha</region>
			</address>
			<address>
				<street>Street: 19 Main St.</street>
				<city>City: damnhour</city>
				<country>Country: Egypt</country>
				<building>Building: 19</building>
				<region>Region: sidi beshr</region>
			</address>
		</addresses>
		<email>Email: rima@yahoo.com</email>
	</employee>
</employees>
